### ISSUE TITLE
doctype

### ISSUE THREAD

**Issue by benkariz** [NERSC/SFAPI.jl#1]
DOCTYPE HTML>
<HTML>
<Head>
<This is the page title</Umoja foundation>
</head>
<Body>
<h1>UMOJA FOUNDATION</h1>
<p>This group started in the year 2005.It was managed by Sir Benjamin KAriuki.By then it had 21 member,after some few years the group grew to a total member of 250 by 2022.
This group has major objectives like;Heiping the needy,orphans,old people among others.</p>
</Body>
</html>

**Comment by jscook2345** [comment]
Spam
